@startuml
set separator none
title PID-Service - Backend - Components

left to right direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

AddElementTag("Element", $bgColor="#1168bd", $borderColor="#0b4884", $fontColor="#ffffff", $sprite="", $shadowing="", $borderStyle="solid")

AddBoundaryTag("Element", $bgColor="#ffffff", $borderColor="#0b4884", $fontColor="#0b4884", $shadowing="", $borderStyle="solid")

Container_Boundary("PIDService.Backend_boundary", "Backend", $tags="Element") {
  Component(PIDService.Backend.RESTmitOpenAPISpec, "REST mit OpenAPI Spec", $techn="", $descr="", $tags="Element", $link="")
  Component(PIDService.Backend.PIDspecifcAPI, "PID specifc API", $techn="", $descr="", $tags="Element", $link="")
  Component(PIDService.Backend.RollenRechteManagement, "Rollen/Rechte Management", $techn="", $descr="", $tags="Element", $link="")
}


SHOW_LEGEND(true)
@enduml